#!/bin/bash

function batstate {
	isCharging=$(cat /sys/class/power_supply/BAT0/status)
	if [ "$isCharging" == "Charging" ]; then
		isCharging=$(echo -e "\u2191")
	elif [ "$isCharging" == "Full" ]; then
		isCharging=""
	else
		isCharging=$(echo -e "\u2193")
	fi
	
	isCharging+="$(cat /sys/class/power_supply/BAT0/capacity)%"
	echo $isCharging
}

batstate
